### PR TITLE
remove python 2.7 packages

### PR DESCRIPTION
**Pull request by faroit**
Python 2.7 will not be maintained after January 1, 2020. I would therefore propose to remove all packages that are not compatible at the end of this year. 

Dear package maintainers, feel free to drop a comment here when your package is made compatible to python 3 in the meantime. I will then update this PR. Thanks for your hard work!

# Python 3 (in-)compatibility list

* [x] [NUSSL](https://interactiveaudiolab.github.io/nussl/)[:octocat:](https://github.com/interactiveaudiolab/nussl) [:package:](https://pypi.python.org/pypi/nussl) - Various source separation algorithms + framework.

@ethman @pseeth 

* [x] [pyFASST](https://github.com/wslihgt/pyfasst)² [:octocat:](https://github.com/wslihgt/pyfasst) [:package:](https://pypi.python.org/pypi/pyFASST) - Wrapper for Flexible Audio Source Separation Toolbox.

@wslihgt

* [x] [dejavu](http://willdrevo.com/fingerprinting-and-audio-recognition-with-python/) [:octocat:](https://github.com/worldveil/dejavu) [:package:](https://pypi.python.org/pypi/PyDejavu) - Audio fingerprinting and recognition.

@worldveil @mauriciorepetto

* [x] [TimeSide](https://github.com/Parisson/TimeSide)² [:octocat:](https://github.com/Parisson/TimeSide) - high level audio analysis, imaging, transcoding, streaming and labelling.

@piem @Tointoin @yomguy

### CODE REVIEW

**Comment by faroit** [comment]
@mauriciorepetto :+1: brilliant. let me know when that is merged so I can remove it from this list!

**Comment by mauriciorepetto** [comment]
That's on @worldveil :) so let's wait on him to approve and merge that.

**Comment by edudobay** [comment]
Hey @faroit! Long story short, my Mingus fork https://github.com/edudobay/python-mingus does support Python 3 now, though the original repository has been archived and I haven't heard from the original maintainer @bspaans about it.

I don't know how a case like this should be handled; if you feel that's okay and in no way disrespectful with the original maintainer, you may list my fork as a Python 3-compatible alternative to the original project.

I had submitted a PR to have Mingus support Python 3, but I had no response from the maintainer and afterwards the original repository was archived.

I've made some more changes to my fork, but I'm not _actively_ maintaining it. Though if there's demand from the community I'd be glad to step up to being a maintainer (so that I could upload the updated version to PyPI and whatnot).

**Comment by bspaans** [comment]
Hey @edudobay, sorry for missing the great work you've been doing. I don't have any time to be involved with maintenance, hence why the repo is archived, but if you'd like I can add you as a collaborator on the project? Not sure how to handle PyPI, but I think I can either transfer or share the mingus namespace with you, so that you can upload a new release. Let me know what you think.

**Comment by edudobay** [comment]
Hey @bspaans, I'd be happy to be added as a colaborator, and I think you could share the PyPI namespace with me if that's okay. Apart from the Python 3 changes, I've made some minor changes for ease of maintenance (e.g. running the `black` source formatter to keep a consistent coding style). Anyway, to avoid unnecessary noise in this thread I'd suggest moving the discussion to your repo or my fork. Because this is your project and I've never taken a big contribution on someone else's project, I'd like to know if you have thoughts about how the project should be carried on.

**Comment by yomguy** [comment]
Hi!
Just to mention that TimeSide is currently in high development and then should not be removed from this list. Moreover, it should be listed in MIR rather than Web Audio.
Thanks!

**Comment by yomguy** [comment]
What about to merge `Feature extraction` and `Music Information Retrieval` ?

**Comment by faroit** [comment]
@yomguy 

> What about to merge Feature extraction and Music Information Retrieval lists?

I am not so sure about this one. Maybe better would be to create a generic audio/music processing tools section. I would probably through in `aubio`, `timeside` and `essentia` in that category. What do you think?

**Comment by faroit** [comment]
>  Just to mention that TimeSide is currently in high development and then should not be removed from this list. 

Great, as soon as you have some beta builds, keep me posted here.

**Comment by faroit** [comment]
@edudobay @bspaans I'm okay with linking to the fork. @edudobay I would suggest you remove the "forked" status once you agreed on how to continue the project.

**Comment by yomguy** [comment]
> @yomguy
> 
> > What about to merge Feature extraction and Music Information Retrieval lists?
> 
> I am not so sure about this one. Maybe better would be to create a generic audio/music processing tools section. I would probably through in `aubio`, `timeside` and `essentia` in that category. What do you think?

Yes, this was my idea merging the two sections. I would agree with "Generic audio processing", maybe "music" should be kept for more symbolic tools not related to audio at all. And maybe leaving specific audio tools in other sections, like "Speech processing".

@piem what do you think?

**Comment by yomguy** [comment]
> > Just to mention that TimeSide is currently in high development and then should not be removed from this list.
> 
> Great, as soon as you have some beta builds, keep me posted here.

OK, sure!
Thanks

**Comment by edudobay** [comment]
Hi @faroit, and a happy new year! Just dropping by to announce that a new version of Mingus has been released, with Python 3 support :)

**Comment by faroit** [comment]
@edudobay @bspaans thanks, modified in this PR

**Comment by faroit** [comment]
@yomguy is there python 3 release planned for timeside soon?

**Comment by yomguy** [comment]
> @yomguy is there python 3 release planned for timeside soon?

@faroit yes, the dev branch is now Python 3 ready ;)
https://github.com/Parisson/TimeSide/tree/dev

**Comment by faroit** [comment]
okay, @yomguy I re-added timeside, marked as beta. Please drop me a note once its released

**Comment by faroit** [comment]
@pseeth do you have a working beta version of NUSSL for python 3?

**Comment by pseeth** [comment]
It's coming! You can see the progress here: https://github.com/interactiveaudiolab/nussl/tree/refactor

I'll ping when it's pip installable - aiming for next week, hopefully.

**Comment by pseeth** [comment]
nussl is now pip installable and compatible with Python 3!

**Comment by faroit** [comment]
@mauriciorepetto @wslihgt I am merging this now as python 2 cannot be recommended at this point. Feel free to open a PR once your packages are ready for python 3

**Comment by mauriciorepetto** [comment]
@faroit hi! I still don't have any reply from @worldveil, the fork that I've made is still there:  https://github.com/worldveil/dejavu/pull/205

**Comment by faroit** [comment]
> @mauriciorepetto @wslihgt I am merging this now as python 2 cannot be recommended at this point. Feel free to open a PR once your packages are ready for python 3

I appreciate your work. Ping me here once this has been merged

**Comment by mauriciorepetto** [comment]
> > @mauriciorepetto @wslihgt I am merging this now as python 2 cannot be recommended at this point. Feel free to open a PR once your packages are ready for python 3
> 
> I appreciate your work. Ping me here once this has been merged

Will do! thanks :)

**Pull request merged**
