### PR TITLE
Add pyannote.audio

### PR DESCRIPTION
**Pull request by hbredin**

### CODE REVIEW

**Comment by faroit** [comment]
Finally, the famous pyannote ;-)

**Comment by hbredin** [comment]
Not sure about "famous", but definitely trying to reach more people ;-)
Thanks for this repo!

**Comment by faroit** [comment]
btw. I want to reorganize the list. Something like proposed [here](https://github.com/faroit/awesome-python-scientific-audio/pull/21#issuecomment-565054568)

any idea?

**Comment by hbredin** [comment]
> btw. I want to reorganize the list. Something like proposed [here](https://github.com/faroit/awesome-python-scientific-audio/pull/21#issuecomment-565054568)
> 
> any idea?

Finding a non-overlapping partition of all those tools will be difficult! 
I don't have any good idea...

**Pull request merged**
